---
title: '`r format(Sys.Date(), "%B %d, %Y")` - COVID foRecastR'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: journal
    includes:
      after_body: footer.html
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet.extras)
library(tidyverse)
library(data.table)
library(plotly)
library(withr)
library(leaflet)
library(geojsonio)
library(RColorBrewer)
library(sf)


# Load data
us_plots <- readRDS("us_plots.rds")
goodmaps <- readRDS("goodmaps.rds")
barplots <- readRDS("bar_list.rds")

# Label functions
pos_text <- function(data){
    text <- paste("Novel positive cases", data, sep = ": ")
    return(text)
}

avg_7_text <- function(data){
    text <- paste("7-day average", data, sep = ": ")
    return(text)
}

forecast_text <- function(data){
    text <- paste("Forecast", data, sep = ": ")
    return(text)
}

est_r_label <- function(data){
    data <- round(data, 2)
    label <- paste("Estimated R: ", data, sep = "")
    return(label)
}

forecast_r_label <- function(data){
    data <- round(data, 2)
    label <- paste("Forecast R: ", data, sep = "")
    return(label)
}


forecast_inf_label <- function(data){
    data <- floor(data)
    label <- paste("Forecast infections per 100k: ", data, sep = "")
    return(label)
}
```

### Forecasting the COVID19 pandemic in the United States
This dashboard uses confirmed cases and statistical modeling to forecast the next 2 weeks of COVID19.


Row {data-width=1000}
------------------------------------------------------------------

### US - new positive cases +  2 week forecast

```{r, out.width = 4, out.height = 4}
subplot(titleY = TRUE, with_options(list(digits = 1, scipen = 10), ggplotly(us_plots[[1]], tooltip = c("date", "text")))) %>% style(hoverinfo = "skip", traces = c(3,4,5))
```

### US - estimated reproduction number + 2 week forecast
```{r, out.width = 4, out.height = 4}
 subplot(with_options(list(digits = 3), ggplotly(us_plots[[2]], tooltip = c("date", "text"))), titleY = TRUE) %>% style(hoverinfo = "skip", traces = c(0,1,2,3,4,5,6))
```

Row {.tabset}
-----------------------------------------------------------------------
### Estimated R
```{r, out.width = "100%", out.height = "100%"}
states_js <- readRDS('states_js.rds')
state_delta_tibble <- readRDS('state_delta_tibble.rds')

states_js$current_inf <- state_delta_tibble$current_inf
states_js$current_rt <- state_delta_tibble$current_rt
states_js$forecast_inf <- state_delta_tibble$forecast_increase
states_js$inf_100k <- state_delta_tibble$current_inf / (states_js$pop_2014 / 100000)
states_js$forecast_100k <- states_js$inf_100k * (1 + states_js$forecast_inf / 100)

basemap <- leaflet(states_js, options = leafletOptions(minZoom = 4, maxZoom = 7)) %>%
    setView(-96, 37.8, 4) %>%
    addProviderTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

pos_bins <- c(0, 10, 25, 50, 100, 150, 200, Inf)
pos_pal <- colorBin("inferno", domain = states_js$inf_100k, bins = pos_bins)

pos_labels <- sprintf(
    "<strong>%s</strong><br/>%g cases per 100k population",
    states_js$name, round(states_js$inf_100k,1)
) %>% lapply(htmltools::HTML)

cases_per_100k_map <- basemap %>% addPolygons(
    fillColor = ~pos_pal(inf_100k),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE),
    label = pos_labels,
    labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto")) %>%
    addLegend(pal = pos_pal, values = ~inf_100k, opacity = 0.7, title = "Cases per 100k",
              position = "bottomright", na.label = element_blank()) %>% suspendScroll(sleepOpacity = 0.9)

r_bins <- c(Inf, 1.3, 1.2, 1.1, 1, 0.9, 0.8, 0.7,-Inf)
r_pal <- colorBin(c("#e41a1c", "#377eb8", "#4daf4a"), domain = states_js$current_rt, bins = r_bins, reverse = TRUE)

r_labels <- sprintf(
    "<strong>%s</strong><br/>%g current R",
    states_js$name, round(states_js$current_rt,2)
) %>% lapply(htmltools::HTML)

current_r_map <- basemap %>% addPolygons(
    fillColor = ~r_pal(current_rt),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE),
    label = r_labels,
    labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto")) %>%
    addLegend(colors = colorBin(c("#e41a1c", "#377eb8", "#4daf4a"),
                                domain = states_js$current_rt, bins = r_bins, reverse = TRUE)(r_bins)[-1], values = ~current_rt, opacity = 0.7, title = "Estimated R",
              position = "bottomright",
              labels = c("> 1.3", "1.2 - 1.3", "1.1 - 1.2", "1.0 - 1.1",
              "0.9 - 1.0", "0.8 - 0.9", "0.7 - 0.8", "< 0.7" )) %>% suspendScroll(sleepOpacity = 0.9)

forecast_labels <- sprintf(
    "<strong>%s</strong><br/>%g Forecast cases per 100k",
    states_js$name, round(states_js$forecast_100k,1)
) %>% lapply(htmltools::HTML)


forecast_map <- basemap %>% addPolygons(
    fillColor = ~pos_pal(forecast_100k),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE),
    label = forecast_labels,
    labelOptions = labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto")) %>%
    addLegend(pal = pos_pal, values = ~forecast_100k, opacity = 0.7, title = "Cases per 100k",
              position = "bottomright") %>% suspendScroll(sleepOpacity = 0.9)


good_map_list <- list(cases_per_100k_map, current_r_map, forecast_map)


good_map_list[[2]]
```

### Positive cases
```{r out.width = "100%", out.height="100%"}
good_map_list[[1]]
```

### Forecast positive cases (+2 weeks)
```{r out.width = "100%", out.height="100%"}
good_map_list[[3]]
```

Row
-----------------------------------------------------------------------
### Current R  

```{r fig.height = 7.5}

r_bar_label <- function(data){
    data <- round(data, 2)
    label <- paste("Current R: ", data, sep = "")
    return(label)
}

current_inf_label <- function(data){
    data <- floor(data)
    label <- paste("Current infections per 100k: ", data, sep = "")
    return(label)
}

forecast_inf_label <- function(data){
    data <- floor(data)
    label <- paste("Forecast % change: ", data, sep = "")
    return(label)
}
barplots[[1]] %>% ggplotly(tooltip = c("region", "text"), height = 700) %>% layout(xaxis = list(side = "top"))

```

### Current infections per 100k  

```{r fig.height = 7.5}
barplots[[2]] %>% ggplotly(tooltip = c("region", "text"), height = 700) %>% layout(xaxis = list(side = "top"))

```

### Forecast infections per 100k (+2 weeks)  

```{r fig.height = 7.5}
barplots[[3]] %>% ggplotly(tooltip = c("region", "text"), height = 700) %>% layout(xaxis = list(side = "top"))

```
